from __future__ import annotations

MODELS = (
    {
        "id": "muse-spark-1.3-contributor-free",
        "zen_endpoint": "responses",
        "context_window": 1000000,
        "max_output_tokens": 131072,
        "reasoning_effort": ["low", "medium", "high"],
        "thinking_toggle": False,
        "tools": True,
        "streaming": True,
        "pricing": {"input": 0, "output": 0},
        "contributor_terms": True,
    },
    {
        "id": "muse-spark-1.2-contributor-free",
        "zen_endpoint": "responses",
        "context_window": 1000000,
        "max_output_tokens": 131072,
        "reasoning_effort": ["low", "medium", "high"],
        "thinking_toggle": False,
        "tools": True,
        "streaming": True,
        "pricing": {"input": 0, "output": 0},
        "contributor_terms": True,
    },
    {
        "id": "deepseek-v4-flash-free",
        "zen_endpoint": "chat",
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort": None,
        "thinking_toggle": True,
        "tools": True,
        "streaming": True,
        "pricing": {"input": 0, "output": 0},
        "contributor_terms": False,
    },
    {
        "id": "mimo-v2.5-free",
        "zen_endpoint": "chat",
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort": None,
        "thinking_toggle": None,
        "tools": True,
        "streaming": True,
        "pricing": {"input": 0, "output": 0},
        "contributor_terms": False,
    },
    {
        "id": "ling-3.0-flash-fin-free",
        "zen_endpoint": "chat",
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort": None,
        "thinking_toggle": None,
        "tools": False,
        "streaming": True,
        "pricing": {"input": 0, "output": 0},
        "contributor_terms": False,
    },
    {
        "id": "nemotron-3-ultra-free",
        "zen_endpoint": "chat",
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort": None,
        "thinking_toggle": None,
        "tools": True,
        "streaming": True,
        "pricing": {"input": 0, "output": 0},
        "contributor_terms": False,
    },
    {
        "id": "nemotron-3.5-lightning-free",
        "zen_endpoint": "chat",
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort": None,
        "thinking_toggle": None,
        "tools": None,
        "streaming": True,
        "pricing": {"input": 0, "output": 0},
        "contributor_terms": False,
    },
    {
        "id": "big-pickle",
        "zen_endpoint": "chat",
        "context_window": None,
        "max_output_tokens": None,
        "reasoning_effort": None,
        "thinking_toggle": None,
        "tools": False,
        "streaming": True,
        "pricing": {"input": 0, "output": 0},
        "contributor_terms": False,
    },
)

BY_ID = {m["id"]: m for m in MODELS}
